-- Q1. What is the total revenue generated by male vs. female customers?
SELECT Gender,sum(purchase_amount) as Total_Revenue
from customer_shopping
Group by Gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id,purchase_amount 
from customer_shopping
WHERE purchase_amount>(SELECT avg(purchase_amount) from customer_shopping)
AND discount_applied = 'YES';

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased,round(avg(review_rating),2) as AVG_review_rating
FROM customer_shopping
GROUP BY item_purchased
ORDER BY avg(review_rating) desc
LIMIT 5;

-- Q4. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer_shopping
GROUP BY age_group
ORDER BY total_revenue desc;

-- Q5. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type,ROUND(AVG(purchase_amount),2) AS AVG_Purchase_Amount  FROM customer_shopping
WHERE shipping_type in('Express','Standard')
GROUP by shipping_type;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer_shopping
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer_shopping
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

-- Q8. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer_shopping
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q9. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer_shopping
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

-- Q10. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer_shopping)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;
 